server:
  port: 8762
#  context-path: /invoice
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://localhost:20001/eureka/,http://localhost:20002/eureka/
      defaultZone: http://localhost:20002/eureka/
#      defaultZone: http://192.168.0.127:20001/eureka/
spring:
  application:
    name: invoice
  profiles:
    #指定读取配置文件:dev(开发环境),prod(生产环境),qa(测试环境)
    active: dev
  redis:
    host: 127.0.0.1
    password: 
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  #数据库连接信息
  datasource:
        name: test
#        url: jdbc:mysql://192.168.1.26:3307/tax-cloud?useUnicode=true&characterEncoding=utf-8&&allowMultiQueries=true
        url: jdbc:mysql://127.0.0.1:3306/tax-cloud?useUnicode=true&characterEncoding=utf-8&&allowMultiQueries=true
        username: root
#        password: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mybatis/mapper/*.xml
   
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  

#日志
logging:
  config: classpath:logback-${spring.profiles.active}.xml
  
  
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000



 
    