server:  
  port: 20002  
eureka:  
  instance:  
    hostname: server2  
  client:  
    #表示是否注册自身到eureka服务器  
    #register-with-eureka: true  
    #是否从eureka上获取注册信息  
    fetch-registry: false  
    service-url:  
      #defaultZone: http://server2:20002/eureka/ 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

   
