
package com.zhys.ys_webservice;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataIOService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://oa.eossoft.com/eosserver/DataIOService.svc?wsdl")
public class DataIOService
    extends Service
{

    private final static URL DATAIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATAIOSERVICE_EXCEPTION;
    private final static QName DATAIOSERVICE_QNAME = new QName("http://tempuri.org/", "DataIOService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://oa.eossoft.com/eosserver/DataIOService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAIOSERVICE_WSDL_LOCATION = url;
        DATAIOSERVICE_EXCEPTION = e;
    }

    public DataIOService() {
        super(__getWsdlLocation(), DATAIOSERVICE_QNAME);
    }

    public DataIOService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAIOSERVICE_QNAME, features);
    }

    public DataIOService(URL wsdlLocation) {
        super(wsdlLocation, DATAIOSERVICE_QNAME);
    }

    public DataIOService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAIOSERVICE_QNAME, features);
    }

    public DataIOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataIOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDataIOService
     */
    @WebEndpoint(name = "BasicHttpBinding_IDataIOService")
    public IDataIOService getBasicHttpBindingIDataIOService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDataIOService"), IDataIOService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDataIOService
     */
    @WebEndpoint(name = "BasicHttpBinding_IDataIOService")
    public IDataIOService getBasicHttpBindingIDataIOService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDataIOService"), IDataIOService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAIOSERVICE_EXCEPTION!= null) {
            throw DATAIOSERVICE_EXCEPTION;
        }
        return DATAIOSERVICE_WSDL_LOCATION;
    }

}

