
package com.zhys.ys_webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IDataIOService", targetNamespace = "http://eossoft.com/WebServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IDataIOService {


    /**
     * 
     * @param userNo
     * @param md5Str
     * @param whereStr
     * @param dataName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDataFromEOS", action = "http://eossoft.com/WebServices/IDataIOService/GetDataFromEOS")
    @WebResult(name = "GetDataFromEOSResult", targetNamespace = "http://eossoft.com/WebServices/")
    @RequestWrapper(localName = "GetDataFromEOS", targetNamespace = "http://eossoft.com/WebServices/", className = "com.zhys.webservice.GetDataFromEOS")
    @ResponseWrapper(localName = "GetDataFromEOSResponse", targetNamespace = "http://eossoft.com/WebServices/", className = "com.zhys.webservice.GetDataFromEOSResponse")
    public String getDataFromEOS(
        @WebParam(name = "UserNo", targetNamespace = "http://eossoft.com/WebServices/")
        String userNo,
        @WebParam(name = "Md5Str", targetNamespace = "http://eossoft.com/WebServices/")
        String md5Str,
        @WebParam(name = "WhereStr", targetNamespace = "http://eossoft.com/WebServices/")
        String whereStr,
        @WebParam(name = "DataName", targetNamespace = "http://eossoft.com/WebServices/")
        String dataName);

    /**
     * 
     * @param dataStr
     * @param userNo
     * @param md5Str
     * @param dataName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendDataToEOS", action = "http://eossoft.com/WebServices/IDataIOService/SendDataToEOS")
    @WebResult(name = "SendDataToEOSResult", targetNamespace = "http://eossoft.com/WebServices/")
    @RequestWrapper(localName = "SendDataToEOS", targetNamespace = "http://eossoft.com/WebServices/", className = "com.zhys.webservice.SendDataToEOS")
    @ResponseWrapper(localName = "SendDataToEOSResponse", targetNamespace = "http://eossoft.com/WebServices/", className = "com.zhys.webservice.SendDataToEOSResponse")
    public String sendDataToEOS(
        @WebParam(name = "UserNo", targetNamespace = "http://eossoft.com/WebServices/")
        String userNo,
        @WebParam(name = "Md5Str", targetNamespace = "http://eossoft.com/WebServices/")
        String md5Str,
        @WebParam(name = "DataName", targetNamespace = "http://eossoft.com/WebServices/")
        String dataName,
        @WebParam(name = "DataStr", targetNamespace = "http://eossoft.com/WebServices/")
        String dataStr);

}

