//
//package com.zhys.webservice;
//
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.xml.bind.annotation.XmlSeeAlso;
//import javax.xml.ws.RequestWrapper;
//import javax.xml.ws.ResponseWrapper;
//
//
///**
// * This class was generated by the JAX-WS RI.
// * JAX-WS RI 2.2.9-b130926.1035
// * Generated source version: 2.2
// * 
// */
//@WebService(name = "InvoiceServicePortType", targetNamespace = "webservices.test.weaver.com.cn")
//@XmlSeeAlso({
//    ObjectFactory.class
//})
//public interface InvoiceServicePortType {
//
//
//    /**
//     * 
//     * @param in0
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod
//    @WebResult(name = "out", targetNamespace = "webservices.test.weaver.com.cn")
//    @RequestWrapper(localName = "docreateInvoice", targetNamespace = "webservices.test.weaver.com.cn", className = "com.zhys.webservice.DocreateInvoice")
//    @ResponseWrapper(localName = "docreateInvoiceResponse", targetNamespace = "webservices.test.weaver.com.cn", className = "com.zhys.webservice.DocreateInvoiceResponse")
//    public String docreateInvoice(
//        @WebParam(name = "in0", targetNamespace = "webservices.test.weaver.com.cn")
//        String in0);
//
//}
